Adding my Canvas Creation to repo
zero-to-mastery/Canvas-Creations pull request #201
Opened 2020-10-14 16:28 UTC by krdormer

Submission for Canvas Creations - Hacktoberfest 2020 @aneagoie

2020-10-16 09:22 UTC, MattCSmith commented
Hey @krdormer, I am unable to resolve the merge conflict on my end. 
Kindly resolve the conflict so we are able to merge it in.

2020-10-21 09:31 UTC, kennithnichol requested changes
I'm not sure why there are so many other users contributions in your commit here.
Perhaps you could try update the PR with the latest from our master?

2020-10-21 09:31 UTC, kennithnichol commented on .gitignore
> -.DS_Store
I don't think we should be replacing the project's .gitignore file here.
You should consider setting your global gitignore to keep your OS and IDE files out of the repository.

Typically the project gitignore would include .DS_Store and Thumbs.db and then any project related exclusions (for example the node_modules or build folders).

reference:
https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files#create-a-global-gitignore

2020-10-22 20:50 UTC, krdormer commented
Apologies, I attempted to submit my work as outlined in the instructions, could I get some clarity on what the conflict is here? 

I see an Art/.DS_Store, and the include.js, but I am not sure how to resolve those conflicts. 

Thank you for any help you may have!

2020-10-23 09:17 UTC, sophiabrandt commented
@krdormer what exactly is your creation? It looks like you change files in several folders?
If possible, please only add your `Art` folder and adjust `include.js`. `include.js` has syntax errors, you'll need to fix them.
Also, remove `.DS_Store` files.

2020-11-11 20:00 UTC, MattCSmith commented
Closing due to age and/or conflicts, feel free to reopen if required. I have also marked this as accepted for the Hacktoberfest challenge as the effort was made.

2020-11-11 20:00 UTC, closed without merging